spring:
  application:
    name: votaciones
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: votaciones
  thymeleaf:
    cache: true

server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/votaciones_db
    username: postgres
    password: postgres
  thymeleaf:
    cache: false

---
spring:
  config:
    activate:
      on-profile: azure
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
