# Build and deploy JAR app to Azure Web App - VotacionescamaraISUD (GRADLE)

name: Build and deploy JAR app to Azure Web App - VotacionescamaraISUD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'   # puedes dejar 'microsoft' si prefieres

      - name: Make gradlew executable
        run: chmod +x gradlew

      # Si tu build.gradle NO está en la raíz, descomenta y ajusta:
      # - name: Move to subdir
      #   run: echo "W_DIR=backend" >> $GITHUB_ENV

      - name: Build with Gradle (bootJar)
        # working-directory: ${{ env.W_DIR }}
        run: ./gradlew clean bootJar -x test

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: build/libs/*.jar   # Gradle deja los jars aquí

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E17D8B73FECF419EB0EB3AEB4BC68498 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9AF3F66E56C1429E9391285FE7F2B4CF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_ABF32F4966A24E41ADF9D3BB8DB52259 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'VotacionescamaraISUD'
          slot-name: 'Production'
          package: '*.jar'   
