name: Build & Deploy (Gradle → Azure Web App)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  APP_NAME: VotacionescamaraISUD          # Nombre del App Service en Azure
  JAVA_VERSION: '17'
  PROJECT_DIR: '.'

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: temurin
          cache: gradle

      - name: Make gradlew executable (if exists)
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          if [ -f "./gradlew" ]; then
            chmod +x ./gradlew
          fi

      # 🔍 Guardas: evita que se cuele el método verCandidatos o mapeos duplicados
      - name: Guard rails - no duplicar mapping /admin/candidatos
        run: |
          set -e
          echo "Verificando duplicados de mappings..."
          if grep -R "verCandidatos" -n src/main/java ; then
            echo "❌ Queda código viejo verCandidatos"; exit 1
          fi
          MULTI=$(grep -R "@GetMapping(\"/admin/candidatos\")" -n src/main/java | wc -l)
          if [ "$MULTI" -gt 1 ]; then
            echo "❌ Hay más de un @GetMapping(\"/admin/candidatos\")"; exit 1
          fi
          echo "✅ Verificación de duplicados correcta."

      # 🧹 Compila en limpio (sin caché)
      - name: Build with Gradle wrapper (if present)
        id: build-with-wrapper
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          if [ -f "./gradlew" ]; then
            ./gradlew --no-build-cache clean bootJar -x test
          else
            echo "no-wrapper" >> $GITHUB_OUTPUT
          fi

      # 🧩 Fallback si no hay wrapper
      - name: Setup Gradle & build (fallback when no wrapper)
        if: steps.build-with-wrapper.outputs.no-wrapper == 'no-wrapper'
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.9

      - name: Build with installed Gradle (fallback)
        if: steps.build-with-wrapper.outputs.no-wrapper == 'no-wrapper'
        working-directory: ${{ env.PROJECT_DIR }}
        run: gradle --no-build-cache clean bootJar -x test

      # 📦 Copia el artefacto generado
      - name: Locate JAR and copy as app.jar
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          JAR_PATH=$(ls build/libs/*-SNAPSHOT.jar build/libs/*.jar 2>/dev/null | head -n1)
          if [ -z "$JAR_PATH" ]; then
            echo "❌ No se encontró ningún JAR en build/libs"; exit 1
          fi
          echo "✅ JAR encontrado: $JAR_PATH"
          cp "$JAR_PATH" "$GITHUB_WORKSPACE/app.jar"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: app.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app
          path: .

      - name: Login to Azure (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E17D8B73FECF419EB0EB3AEB4BC68498 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9AF3F66E56C1429E9391285FE7F2B4CF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_ABF32F4966A24E41ADF9D3BB8DB52259 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.APP_NAME }}
          slot-name: 'Production'
          package: app.jar
